name: Build Debug APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Build APK using Gradle
        run: gradle assembleDebug --warning-mode all

      - name: Upload APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: app/build/outputs/apk/debug/app-debug.apk
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}